%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /path/to/dataset/Kitti/sequences/05

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

display_width : 1024
display_height : 768
display_fx : 400
display_fy : 400
display_cx : 512
display_cy : 384